name: Déploiement

on:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushs vers la branche main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Installer sshpass
      run: |
        sudo apt-get update -y
        sudo apt-get install sshpass -y

    - name: Déployer sur le VPS
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -p "$SSH_PORT" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "cd /var/www/100challenges && git pull"
        sshpass -p "$SSH_PASSWORD" ssh -p "$SSH_PORT" -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" "cd /var/www/100challenges && docker compose --file docker-compose.prod.yaml down && docker compose --file docker-compose.prod.yaml up -d --build"
